/**
 * CoT feature builders for the Search Containment plugin.
 *
 * Shapes mirror what CloudTAK core creates for user-authored features
 * (see `Inputs/RangeRingsInput.vue` and `stores/modules/draw.ts`):
 * `u-d-p` spot markers for points, `u-d-f` for lines.
 */
import { v4 as randomUUID } from 'uuid';
import type { Position } from 'geojson';
import type { Feature } from '../../../src/types.ts';

export const CONTAINMENT_RE = /^Containment (\d+)$/i;

/**
 * Scan existing mission features and return the next free
 * "Containment N" number (max + 1), so repeat runs never collide.
 */
export function nextContainmentNumber(features: Array<{ properties: { callsign?: unknown } }>): number {
    let max = 0;

    for (const feat of features) {
        const callsign = typeof feat.properties.callsign === 'string'
            ? feat.properties.callsign.trim()
            : '';

        const match = CONTAINMENT_RE.exec(callsign);
        if (match) {
            const n = parseInt(match[1], 10);
            if (n > max) max = n;
        }
    }

    return max + 1;
}

/**
 * Build a "Containment {n}" u-d-p spot marker CoT
 */
export function buildContainmentMarker(
    coordinates: Position,
    n: number,
    color: string
): Feature {
    const id = randomUUID();
    const now = new Date().toISOString();

    return {
        id,
        type: 'Feature',
        path: '/',
        properties: {
            id,
            type: 'u-d-p',
            how: 'h-g-i-g-o',
            color,
            archived: true,
            'marker-color': color,
            'marker-opacity': 1,
            time: now,
            start: now,
            stale: now,
            center: [coordinates[0], coordinates[1]],
            callsign: `Containment ${n}`,
            remarks: 'Generated by Search Containment plugin'
        },
        geometry: {
            type: 'Point',
            coordinates: [coordinates[0], coordinates[1]]
        }
    } as Feature;
}

/**
 * Build the containment ring as a closed-LineString u-d-f CoT
 */
export function buildRingFeature(
    ring: Position[],
    callsign: string,
    color: string
): Feature {
    const id = randomUUID();
    const now = new Date().toISOString();

    return {
        id,
        type: 'Feature',
        path: '/',
        properties: {
            id,
            type: 'u-d-f',
            how: 'h-g-i-g-o',
            color,
            stroke: color,
            'stroke-width': 3,
            'stroke-style': 'dashed',
            'stroke-opacity': 1,
            archived: true,
            time: now,
            start: now,
            stale: now,
            center: [ring[0][0], ring[0][1]],
            callsign,
            remarks: 'Generated by Search Containment plugin'
        },
        geometry: {
            type: 'LineString',
            coordinates: ring.map((p) => [p[0], p[1]])
        }
    } as Feature;
}
